"""fix polymorphic identity

Revision ID: 195799a596b2
Revises: dbabdf16b4b9
Create Date: 2026-03-23 22:17:57.747249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '195799a596b2'
down_revision: Union[str, Sequence[str], None] = 'dbabdf16b4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'type',
               existing_type=mysql.ENUM('WALK', 'RUN', 'PUMP', 'PULLUP'),
               type_=sa.Enum('ACTIVITY', 'WALK', 'RUN', 'WORKOUT', name='activitytypes'),
               existing_nullable=False)
    op.add_column('workouts', sa.Column('workout_type', sa.Enum('PUMP', 'PULLUP', name='workouttypes'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'workout_type')
    op.alter_column('activities', 'type',
               existing_type=sa.Enum('ACTIVITY', 'WALK', 'RUN', 'WORKOUT', name='activitytypes'),
               type_=mysql.ENUM('WALK', 'RUN', 'PUMP', 'PULLUP'),
               existing_nullable=False)
    # ### end Alembic commands ###
